apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: comms-external
spec:
  addresses:
<<<<<<< Updated upstream
    - 192.168.5.51-192.168.5.59
    - 192.168.5.241-192.168.5.249
=======
    #- 192.168.5.50/32
    # - 192.168.5.51/32
    - 192.168.5.52/32
    - 192.168.5.53/32
    - 192.168.5.92/32
    - 192.168.5.93/32
    # - 192.168.5.50-192.168.5.59
    # - 192.168.5.241-192.168.5.249
>>>>>>> Stashed changes
