apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: comms-int
  namespace: cert-manager
spec:
  ca:
    secretName: comms-svc-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: comms-svc-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: int.cms.breeze-blocks.net
  secretName: comms-svc-ca-tls
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: comms-svc
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: comms-svc-int
  namespace: cert-manager
spec:
  isCA: true
  commonName: int.cms.breeze-blocks.net
  secretName: comms-svc-int-tls
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: comms-svc-ca
    kind: ClusterIssuer
    group: cert-manager.io
