apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: comms-svc-int
  namespace: cert-manager
spec:
  ca:
    secretName: comms-svc-int
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: comms-svc-int
  namespace: cert-manager
spec:
  isCA: true
  commonName: int.breeze-blocks.net
  secretName: comms-svc-int-tls
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: comms-svc-ca
    kind: ClusterIssuer
    group: cert-manager.io
