apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: comms-svc
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: comms-svc-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: ca.breeze-blocks.net
  secretName: comms-svc-ca
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: comms-svc
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: comms-svc-ca
spec:
  ca:
    secretName: comms-svc-ca-tls
