---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: comms-svc-int
  namespace: cert-manager
spec:
  isCA: true
  commonName: int.cms.breeze-blocks.net
  dnsNames:
    - int.cms.breeze-blocks.net
  emailAddresses:
    - int@breeze-blocks.net
  ipAddresses:
    - 192.168.5.16
  issuerRef:
    name: comms-svc-ca
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    size: 4096
  secretName: comms-svc-int-tls
  usages:
    - cert sign
    - client auth
    - digital signature
    - server auth
    - signing
