apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: thw-svc-int-ca
  namespace: cert-manager
spec:
  ca:
    secretName: thw-svc-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thw-svc-int
  namespace: cert-manager
spec:
  isCA: true
  commonName: thw-int.breeze-blocks.net
  secretName: thw-svc-int-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: thw-svc-int-ca
    kind: ClusterIssuer
    group: cert-manager.io
