apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dynamic-forward-proxy
spec:
  parentRefs:
    - name: {{ .Release.Name }} 
  rules:
    - backendRefs:
      - group: gateway.envoyproxy.io
        kind: Backend
        name: dynamic-resolver
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: dynamic-resolver
spec:
  type: DynamicResolver
  tls:
    wellKnownCACertificates: System
